### PR TITLE
Illustrate usage without Flutter

### PR DESCRIPTION
**Pull request by kuhnroyal**
This shows you how to use the annotations inside the generator without actually adding a dependency.
The only downside is, that you need to move the tests outside of the package.

### CODE REVIEW

**Comment by vasilich6107** [comment]
Thanks for help
I’ll check

**Comment by vasilich6107** [comment]
Nothing changed....
May be I'm missing something?

image

image

**Comment by vasilich6107** [comment]
What command are you using to run tests?

**Comment by kuhnroyal** [comment]
`dart test`

**Comment by vasilich6107** [comment]
haha - nice trick
let me check how code generation in example works

**Comment by vasilich6107** [comment]
@kuhnroyal no way
it works

**Comment by vasilich6107** [comment]
could you explain how you get to that?

**Comment by vasilich6107** [comment]
may be you have a links to articles or other resources...

**Comment by kuhnroyal** [comment]
Well, using `TypeChecker.fromUrl()` you don't need a compile time dependency, which is what prevented the builder from working since it transitively pulled in Flutter.
The `reactive_forms_generator` simply has no dependency on `reactive_forms_annotations` or `reactive_forms`. It will just fail to build if the dependency is not added at runtime. So this may also be a small downside. But a lot of Flutter generators work this way.

**Comment by kuhnroyal** [comment]
I have no articles, I learned this the hard way :)

**Comment by vasilich6107** [comment]
Thanks for sharing this method

**Comment by kuhnroyal** [comment]
This is just less intrusive on `reactive_forms`, thats why I think it would better to start this way. If the split is required later and the generator is stable, can still go for it.

**Comment by vasilich6107** [comment]
Sure. This method will save me a ton of time on convincing maintainer to split ;-)

**Comment by vasilich6107** [comment]
Hi @kuhnroyal 
Thanks again for your help
Currently I made a huge progress in writing generator.
It supports simple form controls, arrays of items, form groups. More features is coming.

The only issue i have for now is debugging tests.
Do you have a working solution how to run test debug with `dart test` in any IDE?

**Comment by kuhnroyal** [comment]
I have not tried that tbh.

**Pull request closed without merging**
